version: '3.3'

services:
    # app:
    #     build:
    #         context: .
    #         dockerfile: ./php/Dockerfile
    #     container_name: laravel_app
    #     restart: unless-stopped
    #     working_dir: /var/www
    #     volumes:
    #         - ./app:/var/www
    #     networks:
    #         - laravel

    web:
        image: nginx:alpine
        container_name: nginx_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./app:/var/www
            - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root_secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
